name: FreezeTag
version: 0.1.8-R0.2-SNAPSHOT
main: net.notexmc.freezetag.FreezeTagPlugin
description: A fun FreezeTag game for Minecraft servers!
website: https://notexmc.net
author: Twily
api-version: 1.20
depend: [ProtocolLib] 
commands:
  lobby:
    description: Go To The FreezeTag Lobby
    aliases: [l]
    usage: /lobby freezetag
  lobbyfreezetag:
    description: go to the freezetag lobby
    aliases: [lft]
    usage: /lobby freezetag
  setlobby:
    description: Set The Main Spawn Point aka The FreezeTag Lobby
    aliases: [sl]
    usage: /setlobby freezetag
    permission: freezetag.setlobby
  setlobbyfreezetag:
    description: Set The Main Spawn Point aka The FreezeTag Lobby
    aliases: [slft]
    usage: /setlobby freezetag
    permission: freezetag.setlobby
  freezetag:
    description: FreezeTag main command
    aliases: [ft]
    usage: /freezetag [subcommands]
    subcommands:
      map:
        description: Manage FreezeTag maps
        permission: freezetag.map
        aliases: [m]
        usage: /freezetag map [subcommands]
        subcommands:
          register:
            description: Register a world as a FreezeTag map
            permission: freezetag.map.register
            aliases: [reg]
            usage: /freezetag map register [worldname]
          delete:
            description: Delete a registered FreezeTag map
            permission: freezetag.map.delete
            aliases: [del]
            usage: /freezetag map delete <worldname>
          list:
          description: List registered FreezeTag maps
          aliases: [ls]
          usage: /freezetag map list
          join:
            description: Join FreezeTag map
            aliases: [j]
            usage: /freezetag map join [random/<mapname>]
permissions:
  freezetag.*:
    description: Allows access to all FreezeTag commands and features.
  freezetag.map:
    description: Alters FreezeTag maps.
  freezetag.map.register:
    description: Register a world as a FreezeTag map.
  freezetag.map.delete:
    description: Delete a registered FreezeTag map.
  freezetag.map.list:
    description: List all the registered maps
  freezetag.setlobby:
    description: Permission To Set A Lobby For The FreezeTag Game.
